### ISSUE TITLE
Further improve command repr by using CaStatusCode

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/caproto#109]
Following up on #107, it would be nice to replace the `status` property on commands, which is currently a plain `int`, with the corresponding `CaStatusCode` object that includes an informative message. I'm not clear on whether the int in `status` is the `code` or the `code_with_severity`. I recall that @klauer dropped all of `_status.py` from heaven. Any guidance, Ken?

**Comment by klauer** [comment]
There's a dictionary in status.py that maps them - use that. It's overly
verbose and confusing, admittedly...
