### ISSUE TITLE
Optimize case where there are too many buffers for sendmsg

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/caproto#113]
It looks like `os.sysconf` could let us see this cutoff coming: https://docs.python.org/3/library/socket.html#socket.socket.sendmsg

**Comment by klauer** [comment]
As a follow-up from before, it's not just buffer count but also per-buffer size. My failing tests were with 2 buffers `(header, payload)` and a 4MB payload, of which about only 100k was sent. A smarter `send` could be written which would still not require a copy as my quick patch did (iterate over `memoryview`'d buffers, see where `send()` last finished, retry from there, etc.)

**Comment by klauer** [comment]
Fix mixed in with #112. It efficiently (I believe) uses`memoryview` slicing with a non-async coroutine (commits: b8f5f21930e54b173b78a1c5642a0ee26cfa7ce8, 90f0118083146fd3816e1d36ed347b5e72fe5c85)
