### ISSUE TITLE
Implement a package-standard way of spawning a repeater

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/caproto#139]
* I have tried a double-fork (see `caproto._utils.spawn_daemon`) but forking does weird things from inside IPython.
* I have tried `Popen`, which works fine by assumes `caproto-repeater` is on the `PATH`. It should be, but calling the function directly smells better to me.

Both of these approaches _always_ spawn a repeater and let that repeater die if it can't bind to the repeater port. This seems wasteful, but I can't think of a better way. The only way to check whether the port is open is to bind to it, and binding to it causes it to become temporarily unavailable (until reclaimed by the OS). So this process seems problematic:

1. Bind to see if it's available.
2. It's available! Start a repeater, which will attempt to bind.

If I understand correctly, (2) can fail depending on race conditions. Better to do: bind and start a repeater or fail to bind and die. But this is admittedly wasteful and I am open to better suggestions! It could be that my understanding of how binding works is not quite right.

**Comment by tacaswell** [comment]
The 'bind and try' approach is what epics-base does

https://github.com/epics-base/epics-base/blob/506be838af320997097bde69c98fcdd0723b7d7e/src/ca/client/udpiiu.cpp#L582-L646

They then use `SO_REUSEADDR` (see https://stackoverflow.com/questions/22549044/why-is-port-not-immediately-released-after-the-socket-closes , http://man7.org/linux/man-pages/man7/socket.7.html ) they spawn the detached process via https://github.com/epics-base/epics-base/blob/506be838af320997097bde69c98fcdd0723b7d7e/src/libCom/osi/os/posix/osdProcess.c#L61-L121 which uses fork + exec which I guess shares that socket state?
