### ISSUE TITLE
Simple example IOC in Windows error message

### ISSUE THREAD

**Issue by johnsinsheimer** [NSLS-II/caproto#174]
I cloned the master branch just now.  Should the simply.py example run properly in Windows yet?
Although I also just realized I don't need to run this in Windows for the application I'm working on...

C:\Users\jsinsheimer\AppData\Local\Continuum\Anaconda3\envs\python=3.6>python "C:\Users\jsinsheimer\AppData\Local\Continuum\Anaconda3\envs\python=3.6\Lib\site-packages\caproto\ioc_examples\simple.py"
PVs: ['simple:A', 'simple:B']
Exception OSError(10022, 'An invalid argument was supplied', None, 10022, None) from selector_select ignored
Traceback (most recent call last):
  File "C:\Users\jsinsheimer\AppData\Local\Continuum\Anaconda3\envs\python=3.6\lib\site-packages\curio\kernel.py", line 739, in _run_coro
    events = selector_select(timeout)
  File "C:\Users\jsinsheimer\AppData\Local\Continuum\Anaconda3\envs\python=3.6\lib\selectors.py", line 323, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "C:\Users\jsinsheimer\AppData\Local\Continuum\Anaconda3\envs\python=3.6\lib\selectors.py", line 314, in _select
    r, w, x = select.select(r, w, w, timeout)
OSError: [WinError 10022] An invalid argument was supplied

**Comment by danielballan** [comment]
You are the first person to test this on Windows. Based on a very cursory preliminary Google search, it looks like the async library curio, which we have used to implement our server, may not support Windows.

Another library, trio, explicitly does support Windows. This might be a good enough reason to switch our focus to trio, as we have been strongly considering doing for some time now (see #122). Our choice of curio is historical: trio is even younger than caproto, and it wasn't an option when we started. As intended all along, switching between I/O libs is pretty easy to do.

In the meantime, for your exploratory efforts, it might be best to work on UNIX or OSX machine and come back to Windows later.
