### ISSUE TITLE
Ensure all clients warn if they receive duplicate search responses

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/caproto#175]
A client may receive redundant responses from the same server (via multiple network interfaces) or different servers that have a PV of the same name.  Both cases should be tested.

**Comment by klauer** [comment]
For (1) multiple responses from the same server is problematic, as you can end up creating more than one circuit where unnecessary, depending on the order the packets are received in each search attempt. 

(1) and (2) are really just misconfiguration by the user end (environment variables, and IOC configuration). libca, as far as I know, usually just warns with annoying messages when the same PV is found on different servers, and connects to the first that responds.

**Comment by tacaswell** [comment]
I thought having more than one server providing a PV was part of the design (for redundancy).

**Comment by danielballan** [comment]
Agreed.

Get Outlook for iOS<https://aka.ms/o0ukef>



On Thu, Apr 19, 2018 at 7:39 PM -0400, "Thomas A Caswell" <notifications@github.com<mailto:notifications@github.com>> wrote:


I thought having more than one server providing a PV was part of the design (for redundancy).

**Comment by danielballan** [comment]
Two things on this:

- Agreed that if the client hears the same response more than once due to multiple network interfaces, that constitutes misconfiguration by the user.
- I believe it is a feature not a bug that you can run multiple servers with the same PV. The CA spec is clear that we are supposed to listen to whichever server answer our search response first. This allows use cases like: "We have multiple motors that can all move the same widget, so if one gets unplugged or kicked over, we can still move the widget."

I added a test for "two servers same PV" for the threading client in 74a7a39fc96cfba4652805e837b5b33c85b9ea24 and it does the right thing. Should add one for the other clients too, so I'll leave this open.

**Comment by danielballan** [comment]
I clarified the intent here with Andrew Johnson himself, and I had the wrong idea about the second point above. If two servers answer to same PV, that is misconfiguration and should generate a warning. Failover is intended to be more explicit. A backup server should receive updates about the primary server's health and only start answering SearchRequests if the main server falls over.

I think our threading client issues a warning now if it receives redundant SearchResponses. We should keep this issue open until all the client implementations do the same.

**Comment by danielballan** [comment]
Closed by #249
