### ISSUE TITLE
How to process user callbacks in parallel while guaranteeing ordering?

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/caproto#204]
Review of discussion:

Currently, the default number of workers in the ThreadPoolExecutor that processes user callbacks is 1. If we increase that number, there is the chance that a worker will start processing "Update #2" before another worker is finished processing "Update #1". This could have significantly bad consequences if the updates relate to control flow, such as motors signaling the beginning and end of their movements or acquire bits of detectors going high and low.

How to solve this? If we isolate each PV to a separate queue or bind it to a specific worker, requiring that updates _for a given PV_ be processed serially, with Update #2 only beginning after Update #1 is complete, sibling PVs on a given device might grow wildly out of sync.

But it does seems desirable to find a way to allow some parallelization because user callbacks commonly do I/O and even sleep.

**Comment by tacaswell** [comment]
A custom thread pool with a non-trivial 'affinity' policy? Would require pushing a lot of information down into the control layer though...

To some degree this is probably something the application should take care of and only register light-weight "move it from your queue to mine" operations directly on the PVs.  We could ex, give each top-level ophyd object it's own thread (or group them somehow) so sleeps won't mess with _other_ devices?

**Comment by danielballan** [comment]
That seems right. I liked the idea of "I'll just put in a lock inside my callback," until we realized that order wasn't guaranteed even so. "Move it from your queue to mine," is a better version of that. Group by Devices to keep their components from getting too far out of sync is sensible.

**Comment by danielballan** [comment]
New thought on this: a server only guarantees time ordering per circuit, so it is safe to move from one worker thread per _context_ to one worker thread per circuit.

I think we should extend the same approach we have now: give users one thread _pool_ per circuit but put one worker in the pool by default. Leave it up to them whether to turn up the number of workers to get more concurrency in some use case where it is OK to start one job before the previous job has completed.

**Comment by danielballan** [comment]
The idea in my previous comment was implemented some time ago in #320. I think this is the best we can do without adding a bunch of complexity ("a non-trivial affinity policy"). I'm going to close -- feel free to reopen if you thing it's worth going further here.
