### ISSUE TITLE
Review dependencies

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/caproto#209]
I discovered that the servers have a hard ophyd dependency, which I think was not intentional.

Is everyone cool with using pip's optional dependency scheme? Maybe

```
pip install caproto  # the threading client and the sync client will work, but no servers
pip install caproto[async]  # picks up trio, curio
pip install caproto[all]  # picks up numpy, ophyd, asks and whatever else
```

**Comment by klauer** [comment]
That's neat about the optional dependency system and a good idea.

Definitely not intentional with ophyd - but I think it's only due to the conversion functions?
Should move that import to a try/except or into the conversion function itself, perhaps.
