### ISSUE TITLE
Consider moving built-in IOC examples to asyncio

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/caproto#225]
I like trio better, but it would be cool to have the ioc examples runnable with zero deps.

**Comment by danielballan** [comment]
We shouldn't do this until asyncio server implements ThreadsafeQueue (see #233).

**Comment by tacaswell** [comment]
We already have an example (https://github.com/NSLS-II/caproto/blob/master/caproto/ioc_examples/barcode_reader.py ) that only works on asyncio and two that only works with curio so having one more example that does not work on asyncio seems reasonable to me.
