### ISSUE TITLE
Consolidate where DEFAULT_VERSION is set.

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/caproto#302]

**Comment by danielballan** [comment]
Contrary to my memory when I posted this issue, we actually set `DEFAULT_PROTOCOL_VERSION = 13` in exactly one place. And according to [the Version Compatibility section of the 3.16 docs](https://epics.anl.gov/base/R3-16/0-docs/CAproto/index.html) the latest protocol version is 13.

So I guess there is no action required here. Agree, @klauer?

**Comment by klauer** [comment]
I think so. It would be wise to update all instances of 13 to this constant though.
