### ISSUE TITLE
The 'native_data_count' should (maybe?) be interpreted as a *max* data_count.

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/caproto#348]
The native_data_count is what we call the data_count provided on CreateChanResponse. It is (maybe?) supposed to be the *max* size of any future payload, not the current size.

On the client side, maybe we should fail or warn if the server sends a data_payload with data_count > native_data_count. On the server side, we need a way to specify the max size and differentiate that from the current size.

**Comment by klauer** [comment]
I think this is mostly correct as implemented. Closing for now.
