### ISSUE TITLE
Callbacks wrapped with functools.partial don't fire.

### ISSUE THREAD

**Issue by stmudie** [NSLS-II/caproto#395]
Trying to use functools.partial to pass data into the callback function (specifically the pv name). However, the callbacks do not fire when partial is used. Tested with 0.2.2

**Comment by danielballan** [comment]
Thanks for the report, @stmudie. My guess is that you aren’t holding any references to the partial object and it is getting garbage collected. See the Warning box at the end of this section:

https://nsls-ii.github.io/caproto/threading-client.html#subscribe-monitor

**Comment by stmudie** [comment]
Thanks for the quick reply. Yes that fixed it. I had seen that Warning, but clearly missed it significance in this case.

**Comment by danielballan** [comment]
Sure thing!
