### ISSUE TITLE
threading client: add support for multiple attempts of PV.read/PV.write

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/caproto#409]
I could see an argument for putting this in as a keyword argument to `read` and `write`. The default would be configurable by `PV` and also by `Context`, falling back in the same way that logging levels propagate. That is, if a `retry` isn't specified in a given call to `pv.read()`, fall back to `pv.retry`; if that is `None`, fall back to `Context.retry`. The factory default of `Context.retry` would be `1` (try once in total).

**Comment by danielballan** [comment]
Maybe `attempts` would be a better term than `retries` because the meaning of `attempts=1` is unambiguous.

**Comment by klauer** [comment]
This is for the threading client, I assume?

👍 on `attempts` over `retries`.
