### ISSUE TITLE
Report to pypy project issues found during caproto tests

### ISSUE THREAD

**Issue by klauer** [NSLS-II/caproto#445]
Notes from @tacaswell in #438:

> This exposed 2 bugs in pypy (which I need to move over to them eventually)
>
> Bug 1 is that ancestors are not consulted for `_anonymous_` https://bitbucket.org/pypy/pypy/src/271763ca6c718760604b8000ef18892758d39485/lib_pypy/_ctypes/structure.py#lines-196
>
> Bug 2 is in how anonymous names are handled internally https://bitbucket.org/pypy/pypy/src/271763ca6c718760604b8000ef18892758d39485/lib_pypy/_ctypes/structure.py#lines-71:89 Looks like they are flattened and the anonymous field goes away (which seems wrong)

And

> There is an issue with numpy + pypy
> 
> ```
> (Pdb) buffers[2]
> array([3.15])
> (Pdb) memoryview(buffers[2]).cast('b')
> *** TypeError: memoryview: cannot cast between two non-byte formats
> ```
>
> which looks like either a numpy or a pypy bug, but no theories on that.

(Was it casting from big to little endian that caused the TypeError?)

**Comment by tacaswell** [comment]
Created https://bitbucket.org/pypy/pypy/issues/2957, https://bitbucket.org/pypy/pypy/issues/2958, https://bitbucket.org/pypy/pypy/issues/2959.

**Comment by pklaus** [comment]
Thanks for your hard work! Nevertheless it's a pity that there's no progress on those issues on the PyPy bugtrackers.

**Comment by klauer** [comment]
Updated issue links, as pypy appears to have moved from bitbucket... :

https://foss.heptapod.net/pypy/pypy/-/issues/2959
https://foss.heptapod.net/pypy/pypy/-/issues/2958
https://foss.heptapod.net/pypy/pypy/-/issues/2957
