### ISSUE TITLE
bytes(array) bug in Python or numpy

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/caproto#48]
Using Python 3.6.0 and numpy 1.11.2, `bytes(numpy.array([1, 2, 3]))` fails and thus several tests that use that path fail. The nominally equivalent method, `numpy.array([1, 2, 3]).tobytes()` works. This bug was be reproduced on Travis [here](https://travis-ci.org/danielballan/caproto/jobs/225586045).

**Comment by klauer** [comment]
Error shown in travis is as follows:
```python
TypeError: only integer arrays with one element can be converted to an index
```

This is also broken (Python 3.5, 1.11.2)
```python
bytes(numpy.array([integer_value])) 
    => b'\x00' * integer_value
```
However, arrays of length > 1 function correctly in my tests.

This appears to be the source, surprisingly in Python itself: https://bugs.python.org/issue29159

**Comment by tacaswell** [comment]
Nathaniel would be proud!

**Comment by danielballan** [comment]
To surface a comment from that Python bug report: a fix will be back-ported to the next minor release of Python 3.5. We should probably keep our 'hack' around anyway.

**Comment by tacaswell** [comment]
Closing as fixed upstream.
