### ISSUE TITLE
Threading client: handle automatic reconnection

### ISSUE THREAD

**Issue by klauer** [NSLS-II/caproto#76]
Upon unintentional disconnection, PV classes should periodically search and try to reconnect

**Comment by tacaswell** [comment]
It only needs to be periodic if monitoring is used, othewise we can just wait until the user pokes it again.

**Comment by danielballan** [comment]
Note to self: `caproto._cli.monitor` should do this too.

**Comment by klauer** [comment]
Addressed by #161
