### ISSUE TITLE
Revisit ChannelChar __len__ method

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/caproto#93]
The caget-scraping tests break if we set `__len__` to `max_length`, as @tacaswell tried to do in #87. What's the correct length? Do we need to fix the scraping tests? Might need @klauer's rescue, as I have helpfully illustrated with Photoshop:

![help us ken](https://user-images.githubusercontent.com/2279598/30713646-f52b8e36-9edd-11e7-928a-f4e1b1d221a5.png)

**Comment by klauer** [comment]
Addressed in #355
