### ISSUE TITLE
Get all caput tests working

### ISSUE THREAD

**Issue by danielballan** [NSLS-II/caproto#98]
Several entries in the parameterized caput tests are commented out because the data does not round-trip (due to str vs byte issues, etc.)

**Comment by danielballan** [comment]
This is closer, but the new `ChannelByte` test needs to be addressed: https://github.com/NSLS-II/caproto/blob/1403eb1ab5e8513a8cae3f05487375f6de4d7342/caproto/tests/test_server.py#L165

**Comment by klauer** [comment]
Closed as of #351
